### PR TITLE
log config not found

### PR DESCRIPTION
**Pull request by cyberb**
It is usefull to know that you are using a default config.
It would save me an hour.

### CODE REVIEW

**Comment by AzureMarker** [comment]
Does #214 solve this problem?

**Comment by cyberb** [comment]
Well, it does not really say that it is a defailt config or not.
Personally I am not even sure why there is a silent switch to default config. I would prefer a command line config file option and if it not given then defailult.

**Comment by PromoFaux** [comment]
I think it probably makes sense to output that it is reverting to a default config, especially if it is not obvious behaviour.

**Comment by AzureMarker** [comment]
:+1: Ok, then the only thing left is to fix the formatting issue (see the [CI output]).

[CI output]: https://circleci.com/gh/pi-hole/api/5676

**Review by AzureMarker — APPROVED** [review]

**Comment by AzureMarker** [comment]
Thanks for the contribution!

**Pull request merged**
