### PR TITLE
Update to shared memory version 3

### PR DESCRIPTION
**Pull request by AzureMarker**
This version of shared memory is shipped with FTL v4.2.2, however that version of FTL can not be used with the API due to required changes in development such as the settings shared memory block.

This requires that pi-hole/FTL#522 merges, to allow the API to connect to the overTime shared memory block.

### CODE REVIEW

**Comment by DL6ER** [comment]
Does this need to be changed now that we use LCM in FTL?

**Comment by AzureMarker** [comment]
No, this does not need to be changed due to the LCM usage in FTL. The range of items the API accesses is limited by the `OVERTIME_SLOTS` constant, which is set to the same value that FTL uses.

The API requires the shared memory arrays it connects to to be multiples of the struct size. This makes it safe to access any index of the shared memory. Before the LCM change, the API could not connect to the overTime shared memory, and now that it is aligned to the struct size, it can be connected to.

**Review by DL6ER — DISMISSED** [review]

**Comment by AzureMarker** [comment]
There is one issue I noticed last night, so I'm going to hold the merge until it is fixed.

In the new overTime layout, some of the slots at the end of the array are in the future. Previously, every overTime slot was either in the present or past. This change was not considered in this PR until now, so the API may return overTime information for the future slots. A commit will be added which limits overTime data to the past and present.

**Comment by DL6ER** [comment]
It should only be a matter of what you show the user. The `overTime` slots in the future will always be empty (zero).

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
