### PR TITLE
Statically link SQLite and fix MUSL linking

### LINKED ISSUE #129: Support CentOS
Currently, the API is compiled with too new of a glibc version. A fix is to change the build system to use CentOS for building. This would make sure any distro that's at least as new as CentOS can run the API.

If this is done, the DEB build would have to happen in a different step, like how the RPM build is currently.

### PR DESCRIPTION
**Pull request by AzureMarker**
Until now, SQLite and its dependencies were dynamically linked, even in MUSL builds which are supposed to be fully static. This caused even MUSL builds to fail to run in CentOS, which has issues with the linking requirements. By statically linking SQLite, the MUSL build is fully static and can run on CentOS.

The x86_64 build has been replaced by the x86_64-musl build. The MUSL build works on all 64bit platforms, including CentOS, so there is little point in having both normal (glibc) and MUSL x86_64 builds. Also, by replacing the regular build, Core does not have to make any changes to start pulling the MUSL build.

Note that FTL also statically links SQLite, so we are one step closer to removing an explicit SQLite dependency in Core (The shell scripts still require it for interacting with the database).

This change (SQLite) increases the binary size by about 2MB.

Fixes #129

### CODE REVIEW

**Comment by DL6ER** [comment]
Are we sure we want to only provide the MUSL binary? Are there any drawbacks from not using `glibc`?

**Comment by AzureMarker** [comment]
The drawbacks to using MUSL instead of glibc seem to be:
- Increased binary size (1MB or smaller)
- No security updates via dynamic linking if glibc is updated

The benefits seem to outweigh the drawbacks:
- CentOS and other distros without an up-to-date glibc version work without issue
- Works on all x86_64 systems without having to install dependencies

We could only use MUSL for CentOS, we just need to decide if it is worth any complexity or maintenance that comes with that decision.

**Review by DL6ER — APPROVED** [review]
I'm okay with going all-way MUSL if it turns out to work without issues during a future pre-release testing with a sufficient number of different operating systems.

**Comment by AzureMarker** [comment]
Holding this until pi-hole/web#173 merges, so that the API's dev build uses a web interface version which supports a dynamic mount point.

**Pull request merged**
